### ISSUE TITLE
Plain auth error

### ISSUE THREAD

**Issue by marinakr** [zmstone/docker-kafka#3]
`sudo docker-compose exec kafka kafka-configs.sh --zookeeper localhost:2181 --alter --add-config 'SCRAM-SHA-256=[iterations=8192,password=pass],SCRAM-SHA-512=[password=pass]' --entity-type users --entity-name mar`
Error:
`WARNING: The TOPICS variable is not set. Defaulting to a blank string.
ERROR: No container found for kafka_1`

**Comment by zmstone** [comment]
hi. sorry for the late reply, it seems the container failed to start (already exited?) do you have any logs ?

**Comment by marinakr** [comment]
I am not using this container anymore, if you can't reproduce it, you can close this bug
